apiVersion: v1
kind: Service
metadata:
  name: learnk8a
  labels:
    app: learnk8
spec:
  type: NodePort
  ports:
  - port: 80
  # port: is the pod's port, eg: .NET Core uses port 80
    nodePort: 30006
    # nodePort: is the outside facing service's port
    protocol: TCP
  selector:
    app: learnk8